{ pkgs }: {
  deps = [
    pkgs.nodejs
    pkgs.puppeteer
    pkgs.glib
    pkgs.nss
    pkgs.cups
    pkgs.alsaLib
    pkgs.at-spi2-atk
    pkgs.at-spi2-core
    pkgs.gtk3
    pkgs.libdrm
    pkgs.libxkbcommon
    pkgs.xorg.libXcomposite
    pkgs.xorg.libXdamage
    pkgs.xorg.libXext
    pkgs.xorg.libXfixes
    pkgs.xorg.libXi
    pkgs.xorg.libXrandr
    pkgs.xorg.libXrender
    pkgs.xorg.libXtst
    pkgs.xorg.libxcb
    pkgs.xorg.libxshmfence
    pkgs.xorg.libX11
    pkgs.xorg.libXcursor
    pkgs.xorg.libXinerama
    pkgs.xorg.libXss
    pkgs.xorg.libXScrnSaver
  ];
}